version: '3.8'

services:
  rating-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rating-dashboard
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    # Mount environment files
    volumes:
      - ./.env.production:/usr/share/nginx/html/.env
    restart: unless-stopped