version: '3.8'

services:
  rating-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rating-dashboard
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    # If you need to mount environment files
    # volumes:
    #   - ./.env.production:/usr/share/nginx/html/.env
    restart: unless-stopped